config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "static_pages#index"
  resources :chats, only: %i[index new show create] do
    resources :messages, only: %i[create]
  end

  post "chats/:id/ask" => "chats#ask", as: :ask_chat
  
  get "static_pages/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat.rb
class Chat < ApplicationRecord
  include ActionView::RecordIdentifier
  acts_as_chat
  belongs_to :user

  # broadcasts_to ->(chat) { "chat_#{chat.id}" }

  after_update_commit { broadcast_updates! }

  def broadcast_updates!
    last_message = self.messages.last
    role = last_message.role
    sleep 5
    if role == "user"
      broadcast_append_to self, target: "messages", partial: "messages/message", locals: { message: last_message }
      broadcast_append_to self, target: "messages", partial: "messages/typing"
    elsif role == "assistant"
      broadcast_remove_to self, target: "typing"
      broadcast_append_to self, target: "messages", partial: "messages/message", locals: { message: last_message }
    end
  end

  def last_message
    message = self.messages.last
    message
  end

  # def summarize
  #   self.ask "Please summarize the our conversation so far."
  # end
  # def token_count
  #   messages.sum { |m| (m.imput_tokens || 0) + (m.output_tokens || 0) }
  # end
end

app/models/message.rb
class Message < ApplicationRecord
  acts_as_message

  after_create_commit { chat.broadcast_updates! }
end

app/models/tool_call.rb
class ToolCall < ApplicationRecord
  acts_as_tool_call
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :chats
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def index
    @chats = current_user.chats
  end

  def new
    @chat = current_user.chats.new
    @anthropic_models = RubyLLM.models.by_provider("anthropic").chat_models.collect(&:id)
  end

  def show
    @chat = Chat.find(params[:id])
  end

  def ask
    @chat = Chat.find(params[:id])
    # message = params[:message]

    # Turbo::StreamsChannel.broadcast_append_to(
    #   @chat,
    #   target: "messages",
    #   partial: "messages/typing",
    #   )
    # binding.b
    # Turbo::StreamsChannel.broadcast_append_to @chat, target: "messages", partial: "messages/typing"
    chunks = ""
    @chat.ask(params[:message]) do |chunk|
      chunks += chunk.content unless chunk.content.nil?
      Turbo::StreamsChannel.broadcast_append_to(
        @chat,
        target: "assistant_message_#{@chat.messages.last.id}",
        partial: "messages/assistant",
        locals: { message: @chat.messages.last, chunks: },
      )
    end
    # Turbo::StreamsChannel.broadcast_remove_to @chat, target: "messages", partial: "messages/typing"
    # ChatJob.perform_later(@chat.id, params[:message])
    # Turbo::StreamsChannel.broadcast_append_to(
    #   @chat,
    #   target: "messages",
    #   partial: "messages/message",
    #   locals: { message: @chat.messages.last },
    # )
    # chat.ask(message) do |chunk|
    # if chunk == chat.messages.last.to_llm.content[0...chunk.content.length]



    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to @chat }
    end
  end

  def create
      @chat = Chat.new(model_id: params[:chat][:model_id], user: current_user)
      if @chat.save
        redirect_to chat_path(@chat)
      else
        render :new
      end
  end

  # def ask
  #   @chat = Chat.find(params[:id])

  #   Chatjob.perform_later(@chat.id, params[:message])

  #   respond_to do |format|
  #     format.turbo_stream
  #     format.html { redirect_to chat_path(@chat) }
  #   end
  # end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/chats/_chat.html.erb
<p><%= chat %></p>

app/views/chats/index.html.erb
<div>
  <h1 class="font-bold text-4xl">Chats#index</h1>
  <p>Find me in app/views/chats/index.html.erb</p>
  <%= current_user.email %>
  <% @chats.each do |chat| %>
    <%= next if chat.messages.first.nil? %>
    <div class="bg-gray-200 rounded-lg m-8 text-black p-4">
      <%= link_to chat.messages.first.content, chat_path(chat) %>
    </div>
  <% end %>
</div>

<%= link_to "New Chat", new_chat_path %>

app/views/chats/new.html.erb
<div>
  <h1 class="font-bold text-4xl">Chats#new</h1>
  <p>Find me in app/views/chats/new.html.erb</p>
  <%= form_for @chat do |f| %>
    <%= f.label :model_id, "Model Name" %>
    <%= f.select :model_id, @anthropic_models, { include_blank: true } %>
    <%= f.submit %>
  <% end %>
</div>

app/views/chats/show.html.erb
<%= turbo_stream_from @chat %>

<div id="messages">
  <%= render @chat.messages %>
</div>


<%= form_with(url: ask_chat_path(@chat), method: :post) do |f| %>
  <div class="my-5">
    <%= f.text_area :message, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", autofocus: true %>
  </div>
  
  <div class="grid justify-items-end">
    <%= f.button type: :submit, class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" do %>
      <i class="fas fa-paper-plane"></i>
      <span class="pl-2">Send</span>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Salesforce Practice" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container max-w-7xl px-4 mx-auto">
      <%= render partial: "shared/navbar" %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/messages/_assistant.html.erb
<div id=<%= "assistant_message_#{message.id}"%> class="bg-gray-200 rounded-lg text-black">
  <%= chunks %>
</div>

app/views/messages/_form.html.erb
<%= form_with(model: Message.new, url: [chat, chat.messages.new]) do |form| %>
  <div class="my-5">
    <%= form.text_area :content, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", autofocus: true %>
  </div>

  <div class="grid justify-items-end">
    <%= form.button type: submit, class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" do %>
      <i class="fas fa-paper-plane"></i>
      <span class="pl-2">Send</span>
    <% end %>
  </div>
<% end %>

app/views/messages/_message.html.erb
<div id="<%= dom_id(message) %>_messages">
  <% if message.role == "user" %>
    <div class="bg-sky-400 rounded-lg m-8 text-white p-4">
      <%= message.content %>
    </div>
  <% else %>
    <div id=<%= "assistant_message_#{message.id}" %> class="bg-gray-200 rounded-lg m-8 text-black p-4">
      <%= message.content %>
    </div>
  <% end %>
</div>

app/views/messages/_typing.html.erb
<div id="typing" >
  <div class="bg-gray-200 rounded-lg m-8 text-black p-4">
    Typing...
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="bg-white">
  <div class="mx-auto">
    <div class="flex h-16 justify-between">
      <div class="flex">
        <div class="flex shrink-0 items-center">
          <img class="h-8 w-auto" src="https://tailwindcss.com/plus-assets/img/logos/mark.svg?color=indigo&shade=600" alt="Your Company">
        </div>
        <div class="hidden sm:ml-6 sm:flex sm:space-x-8">
          <!-- Current: "border-indigo-500 text-gray-900", Default: "border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700" -->
          <a href="#" class="inline-flex items-center border-b-2 border-indigo-500 px-1 pt-1 text-sm font-medium text-gray-900">Products</a>
          <a href="#" class="inline-flex items-center border-b-2 border-transparent px-1 pt-1 text-sm font-medium text-gray-500 hover:border-gray-300 hover:text-gray-700">Solutions</a>
          <a href="#" class="inline-flex items-center border-b-2 border-transparent px-1 pt-1 text-sm font-medium text-gray-500 hover:border-gray-300 hover:text-gray-700">Platform</a>
          <a href="#" class="inline-flex items-center border-b-2 border-transparent px-1 pt-1 text-sm font-medium text-gray-500 hover:border-gray-300 hover:text-gray-700">Pricing</a>
          <a href="#" class="inline-flex items-center border-b-2 border-transparent px-1 pt-1 text-sm font-medium text-gray-500 hover:border-gray-300 hover:text-gray-700">Customers</a>
        </div>
      </div>
      <div class="hidden sm:ml-6 sm:flex sm:items-center">
        <div class="relative ml-3">
          <% if current_user %>
            <%= link_to "Log out", destroy_user_session_path, class: "text-sm font-medium text-gray-900", method: :delete %>
          <% else %>
            <%= link_to "Log in", new_user_session_path, class: "text-sm font-medium text-gray-900" %>
          <% end %>
        </div>
      </div>
      <div class="-mr-2 flex items-center sm:hidden">
        <!-- Mobile menu button -->
        <button type="button" class="relative inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-100 hover:text-gray-500 focus:ring-2 focus:ring-indigo-500 focus:outline-hidden focus:ring-inset" aria-controls="mobile-menu" aria-expanded="false">
          <span class="absolute -inset-0.5"></span>
          <span class="sr-only">Open main menu</span>
          <!--
            Icon when menu is closed.

            Menu open: "hidden", Menu closed: "block"
          -->
          <svg class="block size-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-slot="icon">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
          </svg>
          <!--
            Icon when menu is open.

            Menu open: "block", Menu closed: "hidden"
          -->
          <svg class="hidden size-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-slot="icon">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
    </div>
  </div>

  <!-- Mobile menu, show/hide based on menu state. -->
  <div class="sm:hidden" id="mobile-menu">
    <div class="space-y-1 pt-2 pb-3">
      <!-- Current: "bg-indigo-50 border-indigo-500 text-indigo-700", Default: "border-transparent text-gray-500 hover:bg-gray-50 hover:border-gray-300 hover:text-gray-700" -->
      <a href="#" class="block border-l-4 border-indigo-500 bg-indigo-50 py-2 pr-4 pl-3 text-base font-medium text-indigo-700">Products</a>
      <a href="#" class="block border-l-4 border-transparent py-2 pr-4 pl-3 text-base font-medium text-gray-500 hover:border-gray-300 hover:bg-gray-50 hover:text-gray-700">Solutions</a>
      <a href="#" class="block border-l-4 border-transparent py-2 pr-4 pl-3 text-base font-medium text-gray-500 hover:border-gray-300 hover:bg-gray-50 hover:text-gray-700">Platform</a>
      <a href="#" class="block border-l-4 border-transparent py-2 pr-4 pl-3 text-base font-medium text-gray-500 hover:border-gray-300 hover:bg-gray-50 hover:text-gray-700">Pricing</a>
      <a href="#" class="block border-l-4 border-transparent py-2 pr-4 pl-3 text-base font-medium text-gray-500 hover:border-gray-300 hover:bg-gray-50 hover:text-gray-700">Customers</a>
    </div>
    <div class="border-t border-gray-200 pt-4 pb-3">
      <div class="flex items-center px-4">
        <div class="shrink-0">
          <img class="size-10 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
        </div>
        <div class="ml-3">
          <div class="text-base font-medium text-gray-800">Tom Cook</div>
          <div class="text-sm font-medium text-gray-500">tom@example.com</div>
        </div>
        <button type="button" class="relative ml-auto shrink-0 rounded-full bg-white p-1 text-gray-400 hover:text-gray-500 focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 focus:outline-hidden">
          <span class="absolute -inset-1.5"></span>
          <span class="sr-only">View notifications</span>
          <svg class="size-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-slot="icon">
            <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 0 0 5.454-1.31A8.967 8.967 0 0 1 18 9.75V9A6 6 0 0 0 6 9v.75a8.967 8.967 0 0 1-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 0 1-5.714 0m5.714 0a3 3 0 1 1-5.714 0" />
          </svg>
        </button>
      </div>
      <div class="mt-3 space-y-1">
        <a href="#" class="block px-4 py-2 text-base font-medium text-gray-500 hover:bg-gray-100 hover:text-gray-800">Your Profile</a>
        <a href="#" class="block px-4 py-2 text-base font-medium text-gray-500 hover:bg-gray-100 hover:text-gray-800">Settings</a>
        <a href="#" class="block px-4 py-2 text-base font-medium text-gray-500 hover:bg-gray-100 hover:text-gray-800">Sign out</a>
      </div>
    </div>
  </div>
</nav>

app/views/static_pages/index.html.erb
<div class="relative isolate overflow-hidden bg-white">
  <div class="mx-auto max-w-7xl px-6 pt-10 pb-24 sm:pb-32 lg:flex lg:px-8 lg:py-40">
    <div class="mx-auto max-w-2xl lg:mx-0 lg:shrink-0 lg:pt-8">
      <div class="mt-24 sm:mt-32 lg:mt-16">
        <a href="#" class="inline-flex space-x-6">
          <span class="rounded-full bg-indigo-600/10 px-3 py-1 text-sm/6 font-semibold text-indigo-600 ring-1 ring-indigo-600/10 ring-inset">What's new</span>
          <span class="inline-flex items-center space-x-2 text-sm/6 font-medium text-gray-600">
            <span>Just shipped v1.0</span>
            <svg class="size-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true" data-slot="icon">
              <path fill-rule="evenodd" d="M8.22 5.22a.75.75 0 0 1 1.06 0l4.25 4.25a.75.75 0 0 1 0 1.06l-4.25 4.25a.75.75 0 0 1-1.06-1.06L11.94 10 8.22 6.28a.75.75 0 0 1 0-1.06Z" clip-rule="evenodd" />
            </svg>
          </span>
        </a>
      </div>
      <h1 class="mt-10 text-5xl font-semibold tracking-tight text-pretty text-gray-900 sm:text-7xl">Deploy to the cloud with confidence</h1>
      <p class="mt-8 text-lg font-medium text-pretty text-gray-500 sm:text-xl/8">Anim aute id magna aliqua ad ad non deserunt sunt. Qui irure qui lorem cupidatat commodo. Elit sunt amet fugiat veniam occaecat.</p>
      <div class="mt-10 flex items-center gap-x-6">
        <a href="#" class="rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-xs hover:bg-indigo-500 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Get started</a>
        <a href="#" class="text-sm/6 font-semibold text-gray-900">Learn more <span aria-hidden="true">→</span></a>
      </div>
    </div>
    <div class="mx-auto mt-16 flex max-w-2xl sm:mt-24 lg:mt-0 lg:mr-0 lg:ml-10 lg:max-w-none lg:flex-none xl:ml-32">
      <div class="max-w-3xl flex-none sm:max-w-5xl lg:max-w-none">
        <div class="-m-2 rounded-xl bg-gray-900/5 p-2 ring-1 ring-gray-900/10 ring-inset lg:-m-4 lg:rounded-2xl lg:p-4">
          <img src="https://tailwindcss.com/plus-assets/img/component-images/project-app-screenshot.png" alt="App screenshot" width="2432" height="1442" class="w-[76rem] rounded-md ring-1 shadow-2xl ring-gray-900/10">
        </div>
      </div>
    </div>
  </div>
</div>